import type { Locale } from '@/lib/i18n/config'
import { legalConfig as c } from '@/lib/legal-config'

export type LegalKey = 'about' | 'contact' | 'privacy' | 'cookies' | 'legal' | 'terms'
export type LegalSection = { title: string; paragraphs?: string[]; items?: string[]; links?: { label: string; href: string }[] }
export type LegalDocument = { title: string; description: string; updatedLabel?: string; intro: string; sections: LegalSection[] }

const providerLinks = {
  vercel: [{ label: 'Vercel — Privacy Notice', href: c.hostingProvider.privacyUrl }, { label: 'Vercel — Terms', href: c.hostingProvider.termsUrl }],
  firebase: [{ label: 'Firebase — Privacy and Security', href: c.dataProvider.privacyUrl }, { label: 'Firebase — Data Processing Terms', href: c.dataProvider.processingTermsUrl }],
}
const mapLinks = [c.mapping.renderer, c.mapping.tiles, c.mapping.schema, { name: `© ${c.mapping.data.name}`, url: c.mapping.data.url }].map(({ name, url }) => ({ label: name, href: url }))

const fr: Record<LegalKey, LegalDocument> = {
  about: { title: 'À propos d’Oxploria', description: 'Mission et fonctionnement du guide touristique web Oxploria.', intro: 'Oxploria relie une ville, une carte et des contenus éditoriaux pour faciliter la découverte de lieux culturels.', sections: [
    { title: 'Notre approche', paragraphs: ['Le service permet d’explorer Barcelone et La Rochelle par ville, catégorie, guide ou proximité. Il fonctionne sans compte utilisateur et sans système de notation.'] },
    { title: 'Une information à vérifier', paragraphs: ['Les horaires, tarifs, conditions d’accès et informations pratiques peuvent évoluer : vérifiez-les auprès du lieu concerné avant de vous déplacer.'] },
    { title: 'Nous écrire', paragraphs: [`Une correction historique, une question ou une proposition culturelle peut être adressée à ${c.contactEmail}.`] },
  ] },
  contact: { title: 'Nous contacter', description: 'Contactez Oxploria pour une question, une correction ou l’exercice de vos droits.', intro: 'Oxploria ne propose pas de formulaire. Le bouton ci-dessous ouvre votre logiciel de messagerie : vous choisissez les informations envoyées.', sections: [
    { title: 'Contact éditorial et général', paragraphs: [`Écrivez à ${c.contactEmail} pour signaler une erreur, proposer une correction ou poser une question sur le service.`] },
    { title: 'Données personnelles', paragraphs: ['Utilisez la même adresse en précisant l’objet de votre demande. Oxploria peut demander les informations raisonnablement nécessaires pour vérifier votre identité.'] },
  ] },
  legal: { title: 'Mentions légales', description: 'Identité de l’éditeur, hébergement, prestataires et propriété intellectuelle du site Oxploria.', updatedLabel: 'Dernière mise à jour : 10 octobre 2026', intro: `Les présentes mentions concernent le site web Oxploria accessible à ${c.publicSiteUrl}.`, sections: [
    { title: 'Éditeur', items: [`Nom commercial : ${c.tradeName}`, `Exploitant : ${c.operatorName}, ${c.legalForm}`, `SIRET : ${c.siret}`, `Localisation : ${c.publisherLocation}`, `Adresse électronique : ${c.contactEmail}`, `Directeur de la publication : ${c.publicationDirector}`] },
    { title: 'Hébergement', paragraphs: [`Le site est hébergé par ${c.hostingProvider.name}, ${c.hostingProvider.address}. Les requêtes nécessaires à la fourniture et à la sécurisation du site transitent par son infrastructure.`], links: providerLinks.vercel },
    { title: 'Données touristiques et médias', paragraphs: [`Les contenus touristiques sont lus depuis ${c.dataProvider.name}. Le site n’utilise ni Firebase Authentication, ni Firebase Analytics et n’écrit aucune donnée de visiteur dans Firestore.`], links: providerLinks.firebase },
    { title: 'Cartographie', paragraphs: [`La carte est rendue avec ${c.mapping.renderer.name}. Les tuiles sont fournies par ${c.mapping.tiles.name}, selon le schéma ${c.mapping.schema.name}, à partir de données OpenStreetMap. Oxploria ne revendique aucun droit de propriété sur ces données cartographiques.`], links: mapLinks },
    { title: 'Propriété intellectuelle', paragraphs: ['Sauf mention contraire ou licence tierce, la structure, l’identité visuelle et les contenus éditoriaux propres à Oxploria sont protégés. Les photographies, données et éléments tiers restent soumis aux droits, crédits et licences indiqués.'] },
    { title: 'Contact', paragraphs: [`Pour toute question relative au site ou pour signaler un contenu, écrivez à ${c.contactEmail}.`] },
  ] },
  privacy: { title: 'Politique de confidentialité', description: 'Données traitées par Oxploria, finalités, prestataires, conservation et droits des visiteurs.', updatedLabel: 'Dernière mise à jour : 10 octobre 2026', intro: `Oxploria limite les traitements au fonctionnement du site. Le responsable du traitement est ${c.operatorName}, ${c.legalForm}, joignable à ${c.contactEmail}.`, sections: [
    { title: 'Navigation et sécurité', paragraphs: ['L’hébergeur peut traiter l’adresse IP, la date et l’heure, l’URL demandée, le navigateur, le système et des journaux d’erreur. Ces données servent à transmettre les pages, prévenir les abus, diagnostiquer les incidents et sécuriser le service. Le fondement est l’intérêt légitime à fournir et protéger le site. Les durées techniques sont déterminées par Vercel et la configuration du compte.'] },
    { title: 'Préférences sur votre appareil', paragraphs: ['La langue, la ville active et les identifiants de lieux favoris sont enregistrés dans votre navigateur afin de restituer vos choix. Ils ne créent aucun compte, profil publicitaire ou historique de déplacement et ne sont pas écrits dans Firestore.'] },
    { title: 'Géolocalisation', paragraphs: ['La position précise n’est demandée qu’après une action sur « Autour de moi » et avec l’autorisation du navigateur. Elle sert à recentrer la carte, calculer des distances et trier les lieux.', 'Le calcul est effectué dans le navigateur. La position reste en mémoire ; lorsqu’un changement de page est nécessaire, elle peut être placée temporairement dans le stockage de session puis supprimée dès sa lecture. Oxploria ne l’enregistre pas dans Firestore et ne constitue pas d’historique de positions.'] },
    { title: 'Contenus Firebase', paragraphs: ['Cloud Firestore et Firebase Storage fournissent les fiches touristiques et leurs images. Aucune authentification Firebase, mesure Firebase Analytics ou écriture de données visiteur n’est activée.'] },
    { title: 'Contact par courriel', paragraphs: [`Le site ouvre un lien « mailto » et ne collecte pas le message dans un formulaire. Si vous écrivez à ${c.contactEmail}, votre message est traité pour répondre et assurer le suivi nécessaire, puis conservé selon la durée utile et les obligations applicables.`] },
    { title: 'Destinataires et transferts', paragraphs: ['Vercel peut traiter des données techniques pour l’hébergement et Google fournit Firebase. Quand la carte est affichée, le navigateur demande directement les tuiles et polices à OpenFreeMap, qui reçoit donc les informations techniques nécessaires à la requête, notamment l’adresse IP. Ces prestataires peuvent traiter des données hors de l’Espace économique européen selon leurs infrastructures et mécanismes contractuels applicables.'], links: [...providerLinks.vercel.slice(0, 1), ...providerLinks.firebase.slice(1), { label: 'OpenFreeMap', href: c.mapping.tiles.url }] },
    { title: 'Vos droits', paragraphs: [`Selon le traitement, vous pouvez demander l’accès, la rectification, l’effacement, la limitation ou la portabilité, vous opposer à certains traitements et retirer un consentement. Écrivez à ${c.contactEmail}. Vous pouvez aussi déposer une réclamation auprès de la CNIL.`], links: [{ label: 'CNIL — comprendre et exercer vos droits', href: 'https://www.cnil.fr/fr/mes-demarches/les-droits-pour-maitriser-vos-donnees-personnelles' }, { label: 'CNIL — déposer une plainte', href: 'https://www.cnil.fr/fr/plaintes' }] },
    { title: 'Services non activés', paragraphs: ['Aucun compte, paiement, publicité, affiliation, outil de mesure d’audience, Firebase Analytics ou suivi marketing n’est actif. Toute activation future nécessitera une mise à jour et, lorsque la loi l’exige, un consentement.'] },
  ] },
  cookies: { title: 'Cookies et stockage local', description: 'Cookies et stockages locaux utilisés par Oxploria et moyens de les supprimer.', updatedLabel: 'Dernière mise à jour : 10 octobre 2026', intro: 'Oxploria n’utilise aucun cookie publicitaire ou de mesure d’audience. Les stockages présents répondent aux choix du visiteur et au fonctionnement demandé.', sections: [
    { title: 'Cookie de langue', items: ['oxploria-locale — conserve la langue choisie pendant 12 mois ; cookie interne, SameSite=Lax.'] },
    { title: 'Stockage local', items: ['oxploria-locale — restaure la langue ; jusqu’à suppression par le visiteur.', 'oxploria-active-city — restaure la ville ; jusqu’à suppression par le visiteur.', 'oxploria-favourites — conserve uniquement les identifiants des lieux favoris ; jusqu’à suppression par le visiteur.'] },
    { title: 'Stockage de session', items: ['oxploria-pending-location — transfère temporairement des coordonnées après une demande « Autour de moi » lorsqu’un changement de page est nécessaire ; supprimé à sa lecture et, au plus tard, à la fin de la session.'] },
    { title: 'Pourquoi il n’y a pas de bandeau', paragraphs: ['Aucun traceur publicitaire, marketing ou analytique n’est actif. Le cookie de langue et les préférences servent uniquement aux fonctions demandées. La CNIL cite le cookie de préférence linguistique parmi les traceurs susceptibles d’être exemptés de consentement préalable, tout en recommandant une information transparente.'], links: [{ label: 'CNIL — recommandation cookies et traceurs', href: 'https://www.cnil.fr/sites/default/files/2026-01/recommandation_cookies_consolidee.pdf' }] },
    { title: 'Gérer ou effacer', paragraphs: ['Vous pouvez changer la langue et la ville dans l’interface. Pour supprimer favoris et préférences, effacez les données du site dans les réglages du navigateur. Le blocage du stockage peut empêcher la mémorisation de ces choix.'] },
  ] },
  terms: { title: 'Conditions d’utilisation', description: 'Règles d’utilisation, limites des informations touristiques et services tiers d’Oxploria.', updatedLabel: 'Dernière mise à jour : 10 octobre 2026', intro: `L’accès et l’utilisation de ${c.publicSiteUrl} impliquent l’acceptation des présentes conditions. Le service est gratuit, sans compte ni paiement sur le site.`, sections: [
    { title: 'Objet du service', paragraphs: ['Oxploria propose cartes, sélections, fiches et guides éditoriaux pour accompagner une découverte touristique. Le service ne vend actuellement aucun billet, séjour ou prestation.'] },
    { title: 'Informations touristiques', paragraphs: ['Les contenus sont informatifs. Horaires, tarifs, accès, fermetures, sécurité et accessibilité peuvent évoluer. Vérifiez les informations déterminantes auprès du lieu ou de l’autorité compétente.'] },
    { title: 'Géolocalisation et itinéraires', paragraphs: ['La proximité et les distances sont des estimations calculées à partir de la position du navigateur. Elles ne remplacent pas un système de navigation ou les conditions réelles. Google Maps ne s’ouvre qu’après une action de l’utilisateur et applique ses propres conditions.'] },
    { title: 'Disponibilité', paragraphs: ['Oxploria peut modifier ou interrompre une fonction pour maintenance, sécurité ou évolution. Les limitations de responsabilité s’appliquent uniquement dans les limites autorisées par la loi.'] },
    { title: 'Utilisation acceptable', items: ['Ne pas contourner les mesures de sécurité ni perturber le service.', 'Ne pas extraire massivement les contenus ni enfreindre les droits ou licences applicables.', 'Ne pas utiliser le site à des fins illicites ou portant atteinte aux tiers.'] },
    { title: 'Liens et tiers', paragraphs: ['Les sites touristiques, coordonnées de contact, Google Maps et fournisseurs liés appliquent leurs propres conditions et politiques. Oxploria ne contrôle pas leur contenu ni leur disponibilité.'] },
    { title: 'Droits sur les contenus et la carte', paragraphs: ['Les contenus propres et l’identité visuelle sont protégés. Les cartes et données ouvertes restent régies par les licences de MapLibre, OpenFreeMap, OpenMapTiles et OpenStreetMap indiquées dans les mentions légales et sur la carte.'] },
    { title: 'Droit applicable et contact', paragraphs: [`Le droit français s’applique, sous réserve des dispositions impératives protégeant les consommateurs. Pour rechercher une solution amiable, écrivez d’abord à ${c.contactEmail}.`] },
  ] },
}

function translated(locale: 'es' | 'en'): Record<LegalKey, LegalDocument> {
  const isEs = locale === 'es'
  const t = (es: string, en: string) => isEs ? es : en
  const updatedLabel = t('Última actualización: 10 de octubre de 2026', 'Last updated: 10 October 2026')
  const docs: Record<LegalKey, LegalDocument> = {
    about: { title: t('Acerca de Oxploria', 'About Oxploria'), description: t('Misión y funcionamiento de la guía turística web Oxploria.', 'Purpose and operation of the Oxploria web travel guide.'), intro: t('Oxploria conecta una ciudad, un mapa y contenidos editoriales para facilitar el descubrimiento cultural.', 'Oxploria connects a city, a map and editorial content to make cultural discovery easier.'), sections: [
      { title: t('Nuestro enfoque', 'Our approach'), paragraphs: [t('Explora Barcelona y La Rochelle por ciudad, categoría, guía o proximidad, sin cuenta ni sistema de valoración.', 'Explore Barcelona and La Rochelle by city, category, guide or proximity, without an account or rating system.')] },
      { title: t('Información que conviene comprobar', 'Information to check'), paragraphs: [t('Horarios, precios, acceso y datos prácticos pueden cambiar. Confírmalos antes de desplazarte.', 'Hours, prices, access and practical details may change. Confirm them before travelling.')] },
      { title: t('Escríbenos', 'Write to us'), paragraphs: [t(`Envía preguntas o correcciones a ${c.contactEmail}.`, `Send questions or corrections to ${c.contactEmail}.`)] },
    ] },
    contact: { title: t('Contacto', 'Contact us'), description: t('Contacta con Oxploria para una consulta, corrección o solicitud de derechos.', 'Contact Oxploria with a question, correction or rights request.'), intro: t('No hay formulario: el botón abre tu aplicación de correo y tú eliges qué enviar.', 'There is no form: the button opens your email app and you choose what to send.'), sections: [
      { title: t('Contacto general', 'General contact'), paragraphs: [t(`Escribe a ${c.contactEmail} para señalar un error o hacer una consulta.`, `Email ${c.contactEmail} to report an error or ask a question.`)] },
      { title: t('Datos personales', 'Personal data'), paragraphs: [t('Indica el objeto de la solicitud. Podemos pedir lo razonablemente necesario para verificar tu identidad.', 'State the purpose of the request. We may ask for what is reasonably needed to verify your identity.')] },
    ] },
    legal: { title: t('Aviso legal', 'Legal notice'), description: t('Identidad del editor, alojamiento, proveedores y propiedad intelectual.', 'Publisher identity, hosting, providers and intellectual property.'), updatedLabel, intro: t(`Este aviso se refiere a ${c.publicSiteUrl}.`, `This notice applies to ${c.publicSiteUrl}.`), sections: [
      { title: t('Editor', 'Publisher'), items: [t(`Nombre comercial: ${c.tradeName}`, `Trading name: ${c.tradeName}`), t(`Titular: ${c.operatorName}, empresario individual (microempresario)`, `Operator: ${c.operatorName}, French sole trader (micro-enterprise)`), `SIRET: ${c.siret}`, t(`Ubicación: ${c.publisherLocation}`, `Location: ${c.publisherLocation}`), t(`Correo: ${c.contactEmail}`, `Email: ${c.contactEmail}`), t(`Director de publicación: ${c.publicationDirector}`, `Publication director: ${c.publicationDirector}`)] },
      { title: t('Alojamiento', 'Hosting'), paragraphs: [t(`Alojado por ${c.hostingProvider.name}, ${c.hostingProvider.address}. Las solicitudes técnicas pasan por su infraestructura.`, `Hosted by ${c.hostingProvider.name}, ${c.hostingProvider.address}. Technical requests pass through its infrastructure.`)], links: providerLinks.vercel },
      { title: t('Datos turísticos y medios', 'Tourism data and media'), paragraphs: [t(`Los contenidos se leen desde ${c.dataProvider.name}. No hay Firebase Authentication, Firebase Analytics ni escritura de datos de visitantes.`, `Content is read from ${c.dataProvider.name}. Firebase Authentication, Firebase Analytics and visitor-data writes are not used.`)], links: providerLinks.firebase },
      { title: t('Cartografía', 'Maps'), paragraphs: [t(`Mapa renderizado con ${c.mapping.renderer.name}; mosaicos de ${c.mapping.tiles.name}, esquema ${c.mapping.schema.name} y datos OpenStreetMap. Oxploria no reivindica su propiedad.`, `Map rendered with ${c.mapping.renderer.name}; tiles from ${c.mapping.tiles.name}, ${c.mapping.schema.name} schema and OpenStreetMap data. Oxploria claims no ownership.`)], links: mapLinks },
      { title: t('Propiedad intelectual', 'Intellectual property'), paragraphs: [t('Los contenidos propios y la identidad visual están protegidos. Los elementos de terceros conservan sus derechos, créditos y licencias.', 'Original content and visual identity are protected. Third-party material remains subject to its rights, credits and licences.')] },
      { title: t('Contacto', 'Contact'), paragraphs: [`${c.contactEmail}`] },
    ] },
    privacy: { title: t('Política de privacidad', 'Privacy policy'), description: t('Datos tratados, fines, proveedores, conservación y derechos.', 'Data handled, purposes, providers, retention and rights.'), updatedLabel, intro: t(`Oxploria limita el tratamiento al funcionamiento del sitio. Responsable: ${c.operatorName}, disponible en ${c.contactEmail}.`, `Oxploria limits processing to operating the site. Controller: ${c.operatorName}, available at ${c.contactEmail}.`), sections: [
      { title: t('Navegación y seguridad', 'Browsing and security'), paragraphs: [t('Vercel puede tratar IP, fecha, URL, navegador, sistema y errores para servir y proteger el sitio, sobre la base del interés legítimo. Sus plazos técnicos dependen del proveedor y de la configuración.', 'Vercel may process IP address, time, URL, browser, system and errors to deliver and protect the site, based on legitimate interest. Technical retention depends on the provider and configuration.')] },
      { title: t('Preferencias en tu dispositivo', 'Preferences on your device'), paragraphs: [t('Idioma, ciudad e identificadores de favoritos se guardan localmente. No crean cuenta, perfil publicitario ni historial, y no se escriben en Firestore.', 'Language, city and favourite identifiers are stored locally. They create no account, ad profile or history and are not written to Firestore.')] },
      { title: t('Geolocalización', 'Geolocation'), paragraphs: [t('La posición precisa solo se solicita tras una acción y permiso del navegador para centrar, calcular distancias y ordenar lugares.', 'Precise location is requested only after an action and browser permission to centre, calculate distance and sort places.'), t('El cálculo se hace en el navegador. La posición puede pasar brevemente por el almacenamiento de sesión y se elimina al leerla. No se guarda en Firestore ni forma un historial.', 'Calculation runs in the browser. Location may briefly pass through session storage and is removed when read. It is not stored in Firestore or used to build a history.')] },
      { title: 'Firebase', paragraphs: [t('Firestore y Storage proporcionan contenidos e imágenes; no hay Auth, Analytics ni escrituras de visitantes.', 'Firestore and Storage provide content and images; there is no Auth, Analytics or visitor-data writing.')] },
      { title: t('Contacto por correo', 'Email contact'), paragraphs: [t(`El sitio abre un enlace mailto. Los mensajes a ${c.contactEmail} se tratan para responder y se conservan solo el tiempo útil y legal.`, `The site opens a mailto link. Messages to ${c.contactEmail} are handled to reply and retained only as operationally and legally needed.`)] },
      { title: t('Destinatarios y transferencias', 'Recipients and transfers'), paragraphs: [t('Vercel aloja el sitio y Google proporciona Firebase. Al mostrar el mapa, el navegador solicita directamente mosaicos y fuentes a OpenFreeMap, que recibe los datos técnicos necesarios, incluida la dirección IP. Puede haber tratamiento fuera del EEE según las garantías aplicables.', 'Vercel hosts the site and Google provides Firebase. When the map is shown, the browser requests tiles and fonts directly from OpenFreeMap, which receives required technical data including the IP address. Processing outside the EEA may occur under applicable safeguards.')], links: [...providerLinks.vercel.slice(0, 1), ...providerLinks.firebase.slice(1), { label: 'OpenFreeMap', href: c.mapping.tiles.url }] },
      { title: t('Tus derechos', 'Your rights'), paragraphs: [t(`Puedes solicitar acceso, rectificación, supresión, limitación o portabilidad, oponerte y retirar el consentimiento escribiendo a ${c.contactEmail}. También puedes reclamar ante la CNIL o tu autoridad local.`, `You may request access, correction, deletion, restriction or portability, object and withdraw consent by emailing ${c.contactEmail}. You may also complain to CNIL or your local authority.`)], links: [{ label: 'CNIL — data rights', href: 'https://www.cnil.fr/fr/mes-demarches/les-droits-pour-maitriser-vos-donnees-personnelles' }] },
      { title: t('Servicios no activados', 'Services not enabled'), paragraphs: [t('No hay cuentas, pagos, publicidad, afiliación, analítica ni seguimiento comercial activos.', 'No accounts, payments, advertising, affiliates, analytics or marketing tracking are active.')] },
    ] },
    cookies: { title: t('Cookies y almacenamiento local', 'Cookies and local storage'), description: t('Cookies y almacenamiento usados por Oxploria y cómo borrarlos.', 'Cookies and browser storage used by Oxploria and how to erase them.'), updatedLabel, intro: t('No se utilizan cookies publicitarias ni analíticas. El almacenamiento responde a las funciones solicitadas.', 'No advertising or analytics cookies are used. Storage supports requested functions.'), sections: [
      { title: t('Cookie de idioma', 'Language cookie'), items: [t('oxploria-locale — idioma elegido, 12 meses; propia, SameSite=Lax.', 'oxploria-locale — selected language, 12 months; first-party, SameSite=Lax.')] },
      { title: t('Almacenamiento local', 'Local storage'), items: ['oxploria-locale — ' + t('idioma, hasta borrado.', 'language, until erased.'), 'oxploria-active-city — ' + t('ciudad, hasta borrado.', 'city, until erased.'), 'oxploria-favourites — ' + t('identificadores de favoritos, hasta borrado.', 'favourite identifiers, until erased.')] },
      { title: t('Almacenamiento de sesión', 'Session storage'), items: ['oxploria-pending-location — ' + t('coordenadas temporales, borradas al leerlas o al finalizar la sesión.', 'temporary coordinates, erased when read or when the session ends.')] },
      { title: t('Por qué no hay banner', 'Why there is no banner'), paragraphs: [t('No hay rastreadores publicitarios, comerciales ni analíticos. La CNIL contempla el cookie de idioma entre los que pueden estar exentos de consentimiento previo.', 'There are no advertising, marketing or analytics trackers. CNIL identifies a language cookie as potentially exempt from prior consent.')], links: [{ label: 'CNIL — cookies guidance', href: 'https://www.cnil.fr/sites/default/files/2026-01/recommandation_cookies_consolidee.pdf' }] },
      { title: t('Gestionar o borrar', 'Manage or erase'), paragraphs: [t('Cambia idioma y ciudad en la interfaz o borra los datos del sitio en el navegador.', 'Change language and city in the interface or erase site data in browser settings.')] },
    ] },
    terms: { title: t('Condiciones de uso', 'Terms of use'), description: t('Reglas de uso y límites de la información turística.', 'Usage rules and limits of tourism information.'), updatedLabel, intro: t(`Usar ${c.publicSiteUrl} implica aceptar estas condiciones. El servicio es gratuito, sin cuenta ni pago.`, `Using ${c.publicSiteUrl} means accepting these terms. The service is free, with no account or payment.`), sections: [
      { title: t('Objeto', 'Purpose'), paragraphs: [t('Oxploria ofrece mapas, fichas y guías; no vende entradas, estancias ni prestaciones.', 'Oxploria provides maps, place pages and guides; it sells no tickets, stays or services.')] },
      { title: t('Información turística', 'Tourism information'), paragraphs: [t('Horarios, precios, accesos, cierres, seguridad y accesibilidad pueden cambiar. Confirma la información esencial.', 'Hours, prices, access, closures, safety and accessibility can change. Confirm essential information.')] },
      { title: t('Geolocalización e itinerarios', 'Geolocation and directions'), paragraphs: [t('Distancias y proximidad son estimaciones. Google Maps solo se abre tras una acción y aplica sus propias condiciones.', 'Distance and proximity are estimates. Google Maps opens only after an action and applies its own terms.')] },
      { title: t('Disponibilidad', 'Availability'), paragraphs: [t('Las funciones pueden cambiar o interrumpirse por mantenimiento o seguridad. Los límites de responsabilidad se aplican solo donde la ley lo permite.', 'Functions may change or be interrupted for maintenance or security. Liability limits apply only where permitted by law.')] },
      { title: t('Uso aceptable', 'Acceptable use'), items: [t('No eludir la seguridad ni perturbar el servicio.', 'Do not bypass security or disrupt the service.'), t('No extraer masivamente contenidos ni infringir derechos.', 'Do not bulk-extract content or infringe rights.'), t('No usar el sitio con fines ilícitos.', 'Do not use the site unlawfully.')] },
      { title: t('Enlaces y terceros', 'Links and third parties'), paragraphs: [t('Los sitios enlazados y proveedores aplican sus propias condiciones y políticas.', 'Linked sites and providers apply their own terms and policies.')] },
      { title: t('Contenidos y mapas', 'Content and maps'), paragraphs: [t('Los contenidos propios están protegidos. MapLibre, OpenFreeMap, OpenMapTiles y OpenStreetMap conservan sus licencias.', 'Original content is protected. MapLibre, OpenFreeMap, OpenMapTiles and OpenStreetMap retain their licences.')] },
      { title: t('Ley y contacto', 'Law and contact'), paragraphs: [t(`Rige el derecho francés, sin perjuicio de la protección imperativa del consumidor. Contacto: ${c.contactEmail}.`, `French law applies, subject to mandatory consumer protection. Contact: ${c.contactEmail}.`)] },
    ] },
  }
  return docs
}

const documents = { fr, es: translated('es'), en: translated('en') } satisfies Record<Locale, Record<LegalKey, LegalDocument>>
export function getLegalDocument(locale: Locale, page: LegalKey): LegalDocument { return documents[locale][page] }
