export const legalConfig = {
  tradeName: 'Oxploria',
  operatorName: 'Kevin Hafsi',
  legalForm: 'Entrepreneur individuel (micro-entrepreneur)',
  siret: '10181386300012',
  publicationDirector: 'Kevin Hafsi',
  publisherLocation: 'La Rochelle, France',
  publisherAddress: null,
  publisherPhone: null,
  contactEmail: 'contact@oxploria.com',
  publicSiteUrl: 'https://www.oxploria.com',
  lastUpdated: '2026-10-10',
  hostingProvider: {
    name: 'Vercel Inc.',
    address: '440 N Barranca Avenue #4133, Covina, CA 91723, United States',
    privacyUrl: 'https://vercel.com/legal/privacy-notice',
    termsUrl: 'https://vercel.com/legal/terms',
  },
  dataProvider: {
    name: 'Google Firebase / Cloud Firestore',
    privacyUrl: 'https://firebase.google.com/support/privacy',
    processingTermsUrl: 'https://firebase.google.com/terms/data-processing-terms/',
  },
  mapping: {
    renderer: { name: 'MapLibre GL JS', url: 'https://maplibre.org/maplibre-gl-js/docs/' },
    tiles: { name: 'OpenFreeMap', url: 'https://openfreemap.org/' },
    schema: { name: 'OpenMapTiles', url: 'https://openmaptiles.org/' },
    data: { name: 'OpenStreetMap contributors', url: 'https://www.openstreetmap.org/copyright' },
  },
} as const
