import type { Locale } from '@/lib/i18n/config'

const fr = {
  localeName: 'Français',
  nav: { explore: 'Explorer', map: 'Carte', guides: 'Guides', cities: 'Villes', about: 'À propos', menu: 'Menu', close: 'Fermer' },
  common: { discover: 'Découvrir', viewAll: 'Tout voir', showMore: 'Afficher plus', back: 'Retour', reset: 'Réinitialiser', close: 'Fermer', open: 'Ouvrir', readMore: 'Lire la suite', minutes: 'min de lecture', results: 'résultats', result: 'résultat', optional: 'Facultatif', breadcrumb: 'Fil d’Ariane', skipToContent: 'Aller au contenu' },
  home: {
    eyebrow: 'Guide touristique interactif',
    title: 'La ville commence ici.',
    intro: 'Explorez les incontournables, les sorties en famille et les lieux cachés sur une carte pensée pour vous guider dans la rue.',
    nearMe: 'Autour de moi',
    exploreMap: 'Explorer la carte',
    chooseCity: 'Choisir une ville',
    benefitsLabel: 'Ce que propose Oxploria',
    benefitMap: 'Carte interactive',
    benefitPlaces: 'Lieux sélectionnés',
    benefitStories: 'Histoires et infos',
    destinationsKicker: 'Destinations',
    citiesTitle: 'Choisissez votre terrain d’exploration.',
    citiesIntro: 'Deux villes sont déjà disponibles. D’autres destinations rejoindront bientôt la carte.',
    openCity: 'Découvrir la ville',
    activeCityTitle: 'Quelle ville voulez-vous explorer maintenant ?',
    activeCityBody: 'Votre choix adapte les sélections ci-dessous et sera retrouvé à votre prochaine visite.',
    selectedCity: 'Votre ville active',
    mustSeeTitle: 'Les incontournables',
    mustSeeBody: 'Les repères à ne pas manquer pour une première découverte de {city}.',
    familyTitle: 'À faire en famille',
    familyBody: 'Des lieux accessibles pour partager {city}, apprendre et prendre le temps ensemble.',
    categoriesTitle: 'Explorez selon vos envies',
    categoriesBody: 'Culture, nature, loisirs ou vie locale : ouvrez directement la bonne sélection à {city}.',
    howKicker: 'Comment ça marche',
    methodTitle: 'De votre écran à la rue, en quatre gestes.',
    methodBody: 'Oxploria relie une ville, une carte et des fiches détaillées pour vous aider à décider où aller et comprendre ce que vous voyez.',
    stepChooseTitle: 'Choisissez une ville',
    stepChooseBody: 'Affichez une sélection locale et cohérente.',
    stepMapTitle: 'Ouvrez la carte',
    stepMapBody: 'Repérez les lieux autour de votre parcours.',
    stepNearTitle: 'Activez Autour de moi',
    stepNearBody: 'Classez les découvertes par proximité.',
    stepStoryTitle: 'Ouvrez une fiche',
    stepStoryBody: 'Retrouvez histoire et informations pratiques.',
    guidesKicker: 'Guides éditoriaux',
    guidesTitle: 'Des parcours pour regarder autrement',
    guidesBody: 'Des itinéraires courts pour relier les lieux et comprendre la ville au fil de la marche.',
  },
  city: { exploreMap: 'Explorer sur la carte', viewNavigation: 'Choisir entre la découverte et la carte', startExploring: 'Commencer à explorer', exploreTitle: 'Découvrir {city}', exploreBody: 'Des repères choisis pour composer votre journée selon l’endroit, l’envie et le moment.', popular: 'Les incontournables', popularBody: 'Les lieux qui racontent le mieux la ville et méritent le détour dès une première visite.', family: 'En famille', familyBody: 'Des idées accessibles pour partager la ville, apprendre et prendre le temps ensemble.', goingOut: 'Où sortir', goingOutBody: 'Bars, restaurants, vie locale et loisirs pour prolonger la découverte après la balade.', editorial: 'La sélection Oxploria', editorialBody: 'Des lieux choisis pour leur histoire, leur singularité et ce qu’ils révèlent de la ville.', nearby: 'Près de vous', nearbyBody: 'Activez votre position pour afficher les lieux les plus proches. En attendant, voici une sélection pour commencer.', nearbyActive: 'Les lieux sont désormais classés selon leur distance depuis votre position.', nearbyAction: 'Voir les lieux proches', categories: 'Explorer par envie', guides: 'Guides de la ville', places: 'lieux à découvrir' },
  map: {
    title: 'Explorer la ville', touristTitle: 'Carte touristique de {city}', search: 'Rechercher un lieu, un style ou une adresse', filters: 'Filtres', discoverFilters: 'Découvrir', categories: 'Catégories', mustSee: 'Incontournables', family: 'En famille', all: 'Tout', nearMe: 'Autour de moi', locating: 'Localisation…', list: 'Liste', map: 'Carte', reset: 'Réinitialiser', discover: 'Voir le lieu', showResults: 'Afficher les résultats', closePreview: 'Fermer l’aperçu', mapUnavailable: 'La carte est momentanément indisponible.', mapUnavailableHelp: 'Utilisez la liste pour continuer votre exploration.', noPlaces: 'Aucun lieu ne correspond à ces filtres.', noPlacesHelp: 'Essayez une autre recherche ou réinitialisez les filtres.', locationInsecure: 'La localisation nécessite une connexion HTTPS. Explorez manuellement en attendant la version sécurisée.', locationDenied: 'L’accès à votre position a été refusé. Vous pouvez toujours choisir une ville.', locationUnavailable: 'Votre position est indisponible pour le moment.', locationTimeout: 'La localisation prend trop de temps. Réessayez ou explorez manuellement.', locationError: 'Impossible de déterminer votre position.', locationUnsupported: 'Ce navigateur ne prend pas en charge la localisation.', locationActive: 'Mode proximité activé. Les lieux sont classés par distance.', userPosition: 'Votre position', nearbyResults: '{count} lieux près de vous', resultsNear: 'Lieux autour de vous', loading: 'Préparation de la carte…' },
  places: { title: 'Tous les lieux', searchTitle: 'Rechercher', categoryTitle: 'Lieux dans cette catégorie', categoryEmpty: 'Aucun lieu dans cette catégorie pour le moment.', categoryEmptyHelp: 'Explorez les autres catégories ou ouvrez la carte pour poursuivre votre découverte.', address: 'Adresse', hours: 'Horaires', price: 'Tarif', website: 'Site internet', phone: 'Téléphone', email: 'E-mail', directions: 'Itinéraire', openMap: 'Voir sur la carte', about: 'L’histoire du lieu', practical: 'Informations pratiques', nearby: 'À proximité', gallery: 'Galerie photos', photoUnavailable: 'Image indisponible', credits: 'Crédits photo', tickets: 'Billets et expériences', inGuide: 'À découvrir dans un guide', save: 'Ajouter aux favoris', saved: 'Retirer des favoris' },
  search: { title: 'Que voulez-vous découvrir ?', description: 'Recherchez parmi les lieux de Barcelone et de La Rochelle.', placeholder: 'Ex. Sagrada Família, marché, architecture…', empty: 'Aucun résultat pour cette recherche.', emptyHelp: 'Vérifiez l’orthographe ou essayez un terme plus large.', initial: 'Commencez à écrire pour explorer les lieux.' },
  guides: { title: 'Guides pour explorer autrement', intro: 'Des itinéraires éditoriaux qui relient les lieux, les quartiers et les histoires.', places: 'Lieux de ce guide', route: 'Voir le parcours sur la carte', related: 'Continuer la lecture', mapCollection: 'Parcours du guide' },
  legal: { aboutTitle: 'À propos d’Oxploria', aboutBody: 'Oxploria est un guide touristique web qui relie une ville, une carte et ses lieux culturels.', contactTitle: 'Nous contacter', contactBody: 'Contactez Oxploria pour une question, une correction ou l’exercice de vos droits.', contactAction: 'Écrire à Oxploria', privacyTitle: 'Confidentialité', privacyBody: 'Découvrez les données traitées par Oxploria, leur finalité et vos droits.', cookiesTitle: 'Cookies', cookiesBody: 'Consultez la liste des préférences enregistrées dans votre navigateur.', legalTitle: 'Mentions légales', legalBody: 'Identité de l’éditeur, hébergement et prestataires techniques d’Oxploria.', termsTitle: 'Conditions d’utilisation', termsBody: 'Règles d’utilisation et limites des informations touristiques proposées par Oxploria.' },
  footer: { pitch: 'La carte culturelle qui vous accompagne dans la rue.', explore: 'Explorer', company: 'Oxploria', legal: 'Informations', language: 'Langues', privacy: 'Confidentialité', cookies: 'Cookies', terms: 'Conditions', rights: 'Tous droits réservés.' },
  errors: { title: 'Quelque chose a dévié du parcours.', body: 'La page n’a pas pu être affichée. Votre exploration peut reprendre depuis l’accueil.', retry: 'Réessayer', home: 'Retour à l’accueil', notFoundTitle: 'Ce lieu n’est pas sur notre carte.', notFoundBody: 'Le lien est peut-être ancien ou l’adresse incomplète.', offline: 'Vous semblez hors ligne. Les pages déjà ouvertes peuvent rester disponibles.' },
  metadata: { homeTitle: 'Oxploria — Découvrez ce qui vous entoure', homeDescription: 'Explorez Barcelone et La Rochelle sur une carte culturelle, puis découvrez l’histoire des monuments et lieux autour de vous.', cityDescription: 'Découvrez les lieux, monuments et histoires de {city} avec la carte culturelle Oxploria.', mapDescription: 'Explorez les lieux culturels de {city} sur une carte interactive Oxploria.', guidesDescription: 'Guides culturels et itinéraires pour découvrir {city} autrement.' }
}

const es: typeof fr = {
  localeName: 'Español',
  nav: { explore: 'Explorar', map: 'Mapa', guides: 'Guías', cities: 'Ciudades', about: 'Acerca de', menu: 'Menú', close: 'Cerrar' },
  common: { discover: 'Descubrir', viewAll: 'Ver todo', showMore: 'Mostrar más', back: 'Volver', reset: 'Restablecer', close: 'Cerrar', open: 'Abrir', readMore: 'Seguir leyendo', minutes: 'min de lectura', results: 'resultados', result: 'resultado', optional: 'Opcional', breadcrumb: 'Migas de pan', skipToContent: 'Saltar al contenido' },
  home: { eyebrow: 'Guía turística interactiva', title: 'La ciudad empieza aquí.', intro: 'Explora los imprescindibles, planes en familia y lugares escondidos en un mapa pensado para guiarte por la calle.', nearMe: 'Cerca de mí', exploreMap: 'Explorar el mapa', chooseCity: 'Elegir una ciudad', benefitsLabel: 'Qué ofrece Oxploria', benefitMap: 'Mapa interactivo', benefitPlaces: 'Lugares seleccionados', benefitStories: 'Historias e información', destinationsKicker: 'Destinos', citiesTitle: 'Elige tu terreno de exploración.', citiesIntro: 'Ya hay dos ciudades disponibles. Pronto se sumarán nuevos destinos al mapa.', openCity: 'Descubrir la ciudad', activeCityTitle: '¿Qué ciudad quieres explorar ahora?', activeCityBody: 'Tu elección adapta las selecciones siguientes y se recordará en tu próxima visita.', selectedCity: 'Tu ciudad activa', mustSeeTitle: 'Imprescindibles', mustSeeBody: 'Los lugares que no te puedes perder en una primera visita a {city}.', familyTitle: 'En familia', familyBody: 'Lugares accesibles para compartir {city}, aprender y disfrutar juntos.', categoriesTitle: 'Explora según tus intereses', categoriesBody: 'Cultura, naturaleza, ocio o vida local: abre directamente la selección adecuada en {city}.', howKicker: 'Cómo funciona', methodTitle: 'De la pantalla a la calle, en cuatro pasos.', methodBody: 'Oxploria conecta una ciudad, un mapa y fichas detalladas para ayudarte a decidir dónde ir y comprender lo que ves.', stepChooseTitle: 'Elige una ciudad', stepChooseBody: 'Descubre una selección local y coherente.', stepMapTitle: 'Abre el mapa', stepMapBody: 'Ubica los lugares cerca de tu recorrido.', stepNearTitle: 'Activa Cerca de mí', stepNearBody: 'Ordena los descubrimientos por proximidad.', stepStoryTitle: 'Abre una ficha', stepStoryBody: 'Consulta la historia y la información práctica.', guidesKicker: 'Guías editoriales', guidesTitle: 'Rutas para mirar de otra manera', guidesBody: 'Itinerarios breves que conectan lugares y explican la ciudad mientras caminas.' },
  city: { exploreMap: 'Explorar en el mapa', viewNavigation: 'Elegir entre descubrir y ver el mapa', startExploring: 'Empezar a explorar', exploreTitle: 'Descubrir {city}', exploreBody: 'Lugares seleccionados para organizar el día según dónde estés, lo que te apetezca y el momento.', popular: 'Imprescindibles', popularBody: 'Los lugares que mejor cuentan la ciudad y merecen una visita desde el primer viaje.', family: 'En familia', familyBody: 'Ideas accesibles para compartir la ciudad, aprender y disfrutar del tiempo juntos.', goingOut: 'Dónde salir', goingOutBody: 'Bares, restaurantes, vida local y ocio para seguir descubriendo después del paseo.', editorial: 'La selección de Oxploria', editorialBody: 'Lugares elegidos por su historia, su singularidad y lo que revelan de la ciudad.', nearby: 'Cerca de ti', nearbyBody: 'Activa tu ubicación para ver los lugares más cercanos. Mientras tanto, aquí tienes una selección para empezar.', nearbyActive: 'Los lugares están ordenados por distancia desde tu posición.', nearbyAction: 'Ver lugares cercanos', categories: 'Explorar por interés', guides: 'Guías de la ciudad', places: 'lugares por descubrir' },
  map: { title: 'Explorar la ciudad', touristTitle: 'Mapa turístico de {city}', search: 'Buscar un lugar, estilo o dirección', filters: 'Filtros', discoverFilters: 'Descubrir', categories: 'Categorías', mustSee: 'Imprescindibles', family: 'En familia', all: 'Todo', nearMe: 'Cerca de mí', locating: 'Localizando…', list: 'Lista', map: 'Mapa', reset: 'Restablecer', discover: 'Ver el lugar', showResults: 'Mostrar resultados', closePreview: 'Cerrar vista previa', mapUnavailable: 'El mapa no está disponible temporalmente.', mapUnavailableHelp: 'Usa la lista para seguir explorando.', noPlaces: 'Ningún lugar coincide con estos filtros.', noPlacesHelp: 'Prueba otra búsqueda o restablece los filtros.', locationInsecure: 'La ubicación requiere una conexión HTTPS. Mientras tanto, explora la ciudad manualmente.', locationDenied: 'Has denegado el acceso a tu ubicación. Puedes elegir una ciudad manualmente.', locationUnavailable: 'Tu posición no está disponible en este momento.', locationTimeout: 'La ubicación tarda demasiado. Inténtalo de nuevo o explora manualmente.', locationError: 'No se pudo determinar tu posición.', locationUnsupported: 'Este navegador no admite la ubicación.', locationActive: 'Modo de proximidad activado. Los lugares están ordenados por distancia.', userPosition: 'Tu posición', nearbyResults: '{count} lugares cerca de ti', resultsNear: 'Lugares a tu alrededor', loading: 'Preparando el mapa…' },
  places: { title: 'Todos los lugares', searchTitle: 'Buscar', categoryTitle: 'Lugares de esta categoría', categoryEmpty: 'Todavía no hay lugares en esta categoría.', categoryEmptyHelp: 'Explora las demás categorías o abre el mapa para continuar descubriendo.', address: 'Dirección', hours: 'Horario', price: 'Precio', website: 'Sitio web', phone: 'Teléfono', email: 'Correo electrónico', directions: 'Cómo llegar', openMap: 'Ver en el mapa', about: 'La historia del lugar', practical: 'Información práctica', nearby: 'Cerca', gallery: 'Galería de fotos', photoUnavailable: 'Imagen no disponible', credits: 'Créditos de las fotos', tickets: 'Entradas y experiencias', inGuide: 'Descúbrelo en una guía', save: 'Añadir a favoritos', saved: 'Quitar de favoritos' },
  search: { title: '¿Qué quieres descubrir?', description: 'Busca entre los lugares de Barcelona y La Rochelle.', placeholder: 'Ej. Sagrada Família, mercado, arquitectura…', empty: 'No hay resultados para esta búsqueda.', emptyHelp: 'Comprueba la ortografía o prueba un término más amplio.', initial: 'Empieza a escribir para explorar lugares.' },
  guides: { title: 'Guías para explorar de otra manera', intro: 'Itinerarios editoriales que conectan lugares, barrios e historias.', places: 'Lugares de esta guía', route: 'Ver la ruta en el mapa', related: 'Seguir leyendo', mapCollection: 'Ruta de la guía' },
  legal: { aboutTitle: 'Acerca de Oxploria', aboutBody: 'Oxploria es una guía turística web que conecta una ciudad, un mapa y sus lugares culturales.', contactTitle: 'Contacto', contactBody: 'Contacta con Oxploria para una consulta, corrección o el ejercicio de tus derechos.', contactAction: 'Escribir a Oxploria', privacyTitle: 'Privacidad', privacyBody: 'Descubre los datos tratados por Oxploria, sus fines y tus derechos.', cookiesTitle: 'Cookies', cookiesBody: 'Consulta las preferencias guardadas en tu navegador.', legalTitle: 'Aviso legal', legalBody: 'Identidad del editor, alojamiento y proveedores técnicos de Oxploria.', termsTitle: 'Condiciones de uso', termsBody: 'Reglas de uso y límites de la información turística de Oxploria.' },
  footer: { pitch: 'El mapa cultural que te acompaña por la calle.', explore: 'Explorar', company: 'Oxploria', legal: 'Información', language: 'Idiomas', privacy: 'Privacidad', cookies: 'Cookies', terms: 'Condiciones', rights: 'Todos los derechos reservados.' },
  errors: { title: 'Algo se ha desviado de la ruta.', body: 'No se pudo mostrar la página. Puedes retomar la exploración desde el inicio.', retry: 'Reintentar', home: 'Volver al inicio', notFoundTitle: 'Este lugar no está en nuestro mapa.', notFoundBody: 'Puede que el enlace sea antiguo o que la dirección esté incompleta.', offline: 'Parece que no tienes conexión. Las páginas ya abiertas pueden seguir disponibles.' },
  metadata: { homeTitle: 'Oxploria — Descubre lo que te rodea', homeDescription: 'Explora Barcelona y La Rochelle en un mapa cultural y descubre la historia de los monumentos y lugares cercanos.', cityDescription: 'Descubre los lugares, monumentos e historias de {city} con el mapa cultural de Oxploria.', mapDescription: 'Explora los lugares culturales de {city} en el mapa interactivo de Oxploria.', guidesDescription: 'Guías culturales e itinerarios para descubrir {city} de otra manera.' }
}

const en: typeof fr = {
  localeName: 'English',
  nav: { explore: 'Explore', map: 'Map', guides: 'Guides', cities: 'Cities', about: 'About', menu: 'Menu', close: 'Close' },
  common: { discover: 'Discover', viewAll: 'View all', showMore: 'Show more', back: 'Back', reset: 'Reset', close: 'Close', open: 'Open', readMore: 'Read more', minutes: 'min read', results: 'results', result: 'result', optional: 'Optional', breadcrumb: 'Breadcrumb', skipToContent: 'Skip to content' },
  home: { eyebrow: 'Interactive travel guide', title: 'The city starts here.', intro: 'Explore must-sees, family outings and hidden places on a map designed to guide you while you walk.', nearMe: 'Near me', exploreMap: 'Explore the map', chooseCity: 'Choose a city', benefitsLabel: 'What Oxploria offers', benefitMap: 'Interactive map', benefitPlaces: 'Curated places', benefitStories: 'Stories and information', destinationsKicker: 'Destinations', citiesTitle: 'Choose your next place to explore.', citiesIntro: 'Two cities are ready to explore. More destinations will join the map soon.', openCity: 'Discover the city', activeCityTitle: 'Which city would you like to explore now?', activeCityBody: 'Your choice updates the selections below and will be remembered on your next visit.', selectedCity: 'Your active city', mustSeeTitle: 'Must-sees', mustSeeBody: 'The landmarks worth seeing on a first visit to {city}.', familyTitle: 'For families', familyBody: 'Easy places for sharing {city}, learning and taking your time together.', categoriesTitle: 'Explore by interest', categoriesBody: 'Culture, nature, activities or local life: open the right selection for {city}.', howKicker: 'How it works', methodTitle: 'From your screen to the street in four steps.', methodBody: 'Oxploria connects a city, a map and detailed place pages to help you choose where to go and understand what you see.', stepChooseTitle: 'Choose a city', stepChooseBody: 'See one clear, local selection.', stepMapTitle: 'Open the map', stepMapBody: 'Find places along your route.', stepNearTitle: 'Turn on Near me', stepNearBody: 'Sort discoveries by distance.', stepStoryTitle: 'Open a place page', stepStoryBody: 'Read its story and practical information.', guidesKicker: 'Editorial guides', guidesTitle: 'Routes that change how you look', guidesBody: 'Short itineraries that connect places and explain the city as you walk.' },
  city: { exploreMap: 'Explore on the map', viewNavigation: 'Choose between discovery and the map', startExploring: 'Start exploring', exploreTitle: 'Discover {city}', exploreBody: 'A curated set of places to shape your day around where you are, what you feel like and the moment.', popular: 'Must-sees', popularBody: 'The places that tell the city’s story best and deserve a stop on a first visit.', family: 'For families', familyBody: 'Easy ideas for sharing the city, learning something new and taking time together.', goingOut: 'Where to go out', goingOutBody: 'Bars, restaurants, local life and leisure to keep exploring after the walk.', editorial: 'The Oxploria edit', editorialBody: 'Places chosen for their story, singular character and what they reveal about the city.', nearby: 'Near you', nearbyBody: 'Turn on your location to see the closest places. Until then, start with this curated selection.', nearbyActive: 'Places are now sorted by distance from your position.', nearbyAction: 'See nearby places', categories: 'Explore by interest', guides: 'City guides', places: 'places to discover' },
  map: { title: 'Explore the city', touristTitle: '{city} tourist map', search: 'Search a place, style or address', filters: 'Filters', discoverFilters: 'Discover', categories: 'Categories', mustSee: 'Must-sees', family: 'For families', all: 'All', nearMe: 'Near me', locating: 'Locating…', list: 'List', map: 'Map', reset: 'Reset', discover: 'View place', showResults: 'Show results', closePreview: 'Close preview', mapUnavailable: 'The map is temporarily unavailable.', mapUnavailableHelp: 'Use the list to keep exploring.', noPlaces: 'No places match these filters.', noPlacesHelp: 'Try another search or reset the filters.', locationInsecure: 'Location requires an HTTPS connection. Explore manually until the secure version is available.', locationDenied: 'Access to your location was denied. You can still choose a city manually.', locationUnavailable: 'Your position is unavailable right now.', locationTimeout: 'Location is taking too long. Try again or explore manually.', locationError: 'We could not determine your position.', locationUnsupported: 'This browser does not support location.', locationActive: 'Nearby mode is on. Places are sorted by distance.', userPosition: 'Your position', nearbyResults: '{count} places near you', resultsNear: 'Places around you', loading: 'Preparing the map…' },
  places: { title: 'All places', searchTitle: 'Search', categoryTitle: 'Places in this category', categoryEmpty: 'There are no places in this category yet.', categoryEmptyHelp: 'Explore the other categories or open the map to keep discovering.', address: 'Address', hours: 'Hours', price: 'Price', website: 'Website', phone: 'Phone', email: 'Email', directions: 'Directions', openMap: 'Open on map', about: 'The story of this place', practical: 'Practical information', nearby: 'Nearby', gallery: 'Photo gallery', photoUnavailable: 'Image unavailable', credits: 'Photo credits', tickets: 'Tickets & experiences', inGuide: 'Discover in a guide', save: 'Add to favourites', saved: 'Remove from favourites' },
  search: { title: 'What would you like to discover?', description: 'Search places across Barcelona and La Rochelle.', placeholder: 'E.g. Sagrada Família, market, architecture…', empty: 'No results for this search.', emptyHelp: 'Check the spelling or try a broader term.', initial: 'Start typing to explore places.' },
  guides: { title: 'Guides for a different kind of exploration', intro: 'Editorial itineraries connecting places, neighbourhoods and stories.', places: 'Places in this guide', route: 'View the route on the map', related: 'Keep reading', mapCollection: 'Guide route' },
  legal: { aboutTitle: 'About Oxploria', aboutBody: 'Oxploria is a web travel guide connecting a city, a map and its cultural places.', contactTitle: 'Contact us', contactBody: 'Contact Oxploria with a question, correction or data-rights request.', contactAction: 'Write to Oxploria', privacyTitle: 'Privacy', privacyBody: 'Learn what Oxploria processes, why, and how to exercise your rights.', cookiesTitle: 'Cookies', cookiesBody: 'Review the preferences stored in your browser.', legalTitle: 'Legal notice', legalBody: 'Oxploria publisher identity, hosting and technical providers.', termsTitle: 'Terms of use', termsBody: 'Usage rules and limits applying to Oxploria tourism information.' },
  footer: { pitch: 'The cultural map that walks the city with you.', explore: 'Explore', company: 'Oxploria', legal: 'Information', language: 'Languages', privacy: 'Privacy', cookies: 'Cookies', terms: 'Terms', rights: 'All rights reserved.' },
  errors: { title: 'Something drifted off route.', body: 'The page could not be displayed. You can resume exploring from the homepage.', retry: 'Try again', home: 'Back to homepage', notFoundTitle: 'This place is not on our map.', notFoundBody: 'The link may be old or the address may be incomplete.', offline: 'You appear to be offline. Pages you already opened may remain available.' },
  metadata: { homeTitle: 'Oxploria — Discover what is around you', homeDescription: 'Explore Barcelona and La Rochelle on a cultural map, then discover the history of landmarks and places around you.', cityDescription: 'Discover the places, landmarks and stories of {city} with the Oxploria cultural map.', mapDescription: 'Explore cultural places in {city} on the interactive Oxploria map.', guidesDescription: 'Cultural guides and itineraries to discover {city} differently.' }
}

export const dictionaries = { fr, es, en }
export type Dictionary = typeof fr

export function getDictionary(locale: Locale): Dictionary {
  return dictionaries[locale]
}
